---
- name: Check Security Vulnerabilities Playbook
  hosts: "{{ target_hosts }}"
  gather_facts: false
  become: true

  tasks:
    - name: Run security vulnerability collector
      ansible.builtin.command:
        cmd: /usr/local/lssecfixes/sbin/collector_secfix.py -l -p -s -x
      register: secfix_output
      changed_when: false

    - name: Display security vulnerability report
      debug:
        msg: "{{ secfix_output.stdout }}"
